### ISSUE TITLE
Question about the Sounds

### ISSUE THREAD

**Issue by fraespre** [jorgegv/rage1#40]
Hi Jorge,

I have a simple question about your Sound system.
Why haven't you used the beepfx library (there are available into the z88dk) ? Instead that, you have extrated the asm code and you have included into your game. What's the benefict ?

thanks in advance.

**Comment by jorgegv** [comment]
Hi fraespe, answered in https://github.com/jorgegv/rage1/discussions/12#discussioncomment-668547, would you mind to continus discussion there, please? ;-)

**Comment by jorgegv** [comment]
https://github.com/jorgegv/rage1/discussions/42
