### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by fraespre** [jorgegv/rage1#75]
hi Jorge ... I've thought we could create a z88dk group in Telegram to help each other.
what do you think about

**Comment by jorgegv** [comment]
Hi fraespre,

well, besides the fact that this is the RAGE1 repo, not Z88DK itself... why not use the [standard Z88DK forums](https://z88dk.org/forum/)? I have found the people there quite responsive...

**Comment by fraespre** [comment]
Sorry Jorge if I've disturbed you. I only wanted to contact you. 
I didn't see any email to do it, so I decided to open this issue.

I know very well the z88dk forums, and I like them a lot to follow some threads. For example, what will be the libraries' future. 
Nevertheless, I guess most forum members won't be interested in a Telegram group.

BR.

**Comment by jorgegv** [comment]
Don't worry, you didn't disturb me. For my part, I'm not feally interested in a new Telegram group - I already have too many active communication channels right now and I don't feel like opening a new one.

Maybe people is not interested in a Telegram group, but people in the Z88DK forums will surely be interested in whatever you want to ask on them, and they (we) will try to help you the best they (we) can.

Have fun
Jorge

**Comment by fraespre** [comment]
ok Jorge, thanks for your advice

**Comment by jorgegv** [comment]
Btw, you can reach me at zx@jogv.es
