### ISSUE TITLE
datagen: add loading SCREEN$ support

### ISSUE THREAD

**Issue by jorgegv** [jorgegv/rage1#78]
Allow specifying a loading screen for the final game TAP

Tasks:

- [x] Add support for `LOADING_SCREEN` directive in GDATA file under `game_config`
- [x] Allow PNG support for loading screen image:
  - [x] Tool for converting PNG to SCR file
  - [x] Add `PNG=`file to `LOADING_SCREEN` directive
- [x] Allow SCR support for loading screen image:
  - [x] Add `SCR=`file to LOADING_SCREEN` directive
  - [x] SCR option has preference over PNG option
- [x] Document everything in `DATAGEN.md`
- [x] Add Makefile support for 48-mode
- [x] Add Makefile support for 128-mode
- [x] Add `WAIT_FOR_KEY` option to `LOADING_SCREEN` directive

**Comment by TheStruggleForAntiSpaghetti** [comment]
Nice options :)
