### ISSUE TITLE
datagen: add CUSTOM_CHARSET support

### ISSUE THREAD

**Issue by jorgegv** [jorgegv/rage1#79]
Allow specifying a character set for the game:

- [x] Directive `CUSTOM_CHARSET` in GDATA file under `game_config`
- [x] Mandatory `FILE=` option in directive, points to data file in binary form. Must be always 768 bytes in size.
- [x] Optional `RANGE=M-N` option in directive to allow specifying only a range of chars to be used. This allows to reduce memory usage, if you only use a subset of all characters (e.g. `32-90` for symbols, numbers and capital letters). Only characters in the range specified are defined.
- [x] Document in DATAGEN.md

**Comment by TheStruggleForAntiSpaghetti** [comment]
Hey, nice work :)
I was thinking about a possible optimisation. As with the limited mem a full charset can be quite costly and mostly not all characters always being used, it would be nice if the start and end characters could be specified. This way, for example, only the numbers and CAPS could be selected and loaded.

**Comment by jorgegv** [comment]
> Hey, nice work :) I was thinking about a possible optimisation. As with the limited mem a full charset can be quite costly and mostly not all characters always being used, it would be nice if the start and end characters could be specified. This way, for example, only the numbers and CAPS could be selected and loaded.

That's exactly what the 3rd paragraph specifies... Maybe you and I were writing on it at the same time? Nice telepathy then! ;-)

**Comment by TheStruggleForAntiSpaghetti** [comment]
Unreal 😀😎
